config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'posts/index'
get 'posts/dashboard', to: 'posts#dashboard'


post 'posts',  to: 'posts#create'

root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title , presence: {message: "title is empty"}
  validates :content , presence: {message: "content is empty"}
  validates :image_url , presence: {message: "image is empty"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only:
  :dashboard


  def index
    @posts = Post.all.reverse

  end

def dashboard
  @post = Post.new
end

def create
  @post = Post.new(post_params)
  s1='spoiler'
  text = @post.content
s1='spoiler'
snew=''
s= text.split(s1)
s.each {|x| snew += x.to_s}
  @post.content = snew

  if @post.save
    redirect_to root_path, notice: 'si guardo'
  else
    render :dashboard, alert: 'no guardo'
end
end

private
 def post_params
   params.require(:post).permit(:title, :image_url, :content)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/dashboard.html.erb
<h1 class="text-center m-4 text-success">Add new post</h1>
<div class="text-center m-4" id="create_posts">
<h2><%=flash[:alert]%></h2>


<div class=" m-4 p-4">
<%= form_with(model:@post, local: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="form-group">
| <%= f.label :title %>
  <%= f.text_field  :title,  class: "form-control" %>
</div>
   <div class="form-group">
  <%= f.label :content %>
  <%=  f.text_area  :content,  class: "form-control" %>
  </div>
   <div class="form-group">
  <%= f.label :image %>
  <%= f.text_area  :image_url,  class: "form-control" %>
</div>
<%= f.submit 'Guadrar', class: "btn, btn-success" %>
  <% end %>
  </div>
  </div>

app/views/posts/index.html.erb
<h1 class="text-center m-4 text-success">MY BLOG</h1>
<h2><%=flash[:notice]%> </h2>


 <%  @posts.each_slice(2) do |post2| %>
  <div class="card-deck">
    <%  post2.each do |post| %>
  <div class="card">
<%= image_tag post.image_url, class: 'card-image-top img-fluid', style: 'height:250px;width:250px' %>
    <div class="card-body">
      <h5 class="card-title">Title</h5>
      <p class="card-text"><%= post.title %></p>
      <h5 class="card-title">Content</h5>
      <p class="card-text"><%= post.content %></p>
      <h5 class="card-title">Created_at</h5>
      <p class="card-text"><%= post.created_at %></p>

  </div>

  </div>
   <% end %>
</div>
<% end %>

<%= link_to "Dashboard", posts_dashboard_path %>